name: ZAP Baseline Scan

on:
  pull_request:
    types: [opened, reopened, synchronize, closed]
    branches:
      - dev

jobs:
  zap-scan:
    name: Run Zap Baseline scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: dev
      - name: ZAP scan
        if: github.event.pull_request.state == 'open'
        # ZAP Scan must be able to log an issue, otherwise it will fail
        uses: zaproxy/action-baseline@v0.3.0
        uses: actions/setup-node@v1
        with:
          target: "https://dev-invasivesbc.pathfinder.gov.bc.ca"
          node-version: 12